# Generated by Django 3.1.2 on 2021-04-01 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the dataset', max_length=250, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_simulations', models.IntegerField(default=0)),
                ('total_nodes', models.IntegerField(default=0)),
                ('max_simulation_nodes', models.IntegerField(default=0)),
                ('min_simulation_nodes', models.IntegerField(default=0)),
                ('simulation_attributes', models.JSONField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dataset',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('file_id', models.IntegerField(db_index=True)),
                ('node_id', models.IntegerField(db_index=True)),
                ('tphys', models.FloatField()),
                ('kstar_1', models.FloatField()),
                ('mass0_1', models.FloatField()),
                ('mass_1', models.FloatField()),
                ('lumin_1', models.FloatField()),
                ('rad_1', models.FloatField()),
                ('teff_1', models.FloatField()),
                ('massc_1', models.FloatField()),
                ('radc_1', models.FloatField()),
                ('menv_1', models.FloatField()),
                ('renv_1', models.FloatField()),
                ('epoch_1', models.FloatField()),
                ('ospin_1', models.FloatField()),
                ('deltam_1', models.FloatField()),
                ('rrol_1', models.FloatField()),
                ('kstar_2', models.FloatField()),
                ('mass0_2', models.FloatField()),
                ('mass_2', models.FloatField()),
                ('lumin_2', models.FloatField()),
                ('rad_2', models.FloatField()),
                ('teff_2', models.FloatField()),
                ('massc_2', models.FloatField()),
                ('radc_2', models.FloatField()),
                ('menv_2', models.FloatField()),
                ('renv_2', models.FloatField()),
                ('epoch_2', models.FloatField()),
                ('ospin_2', models.FloatField()),
                ('deltam_2', models.FloatField()),
                ('rrol_2', models.FloatField()),
                ('porb', models.FloatField()),
                ('sep', models.FloatField()),
                ('ecc', models.FloatField()),
                ('b_0_1', models.FloatField()),
                ('b_0_2', models.FloatField()),
                ('snkick_1', models.FloatField()),
                ('snkick_2', models.FloatField()),
                ('vsys_final', models.FloatField()),
                ('sntheta_final', models.FloatField()),
                ('sn_1', models.FloatField()),
                ('sn_2', models.FloatField()),
                ('bin_state', models.FloatField()),
                ('merger_type', models.FloatField()),
                ('bin_num', models.FloatField()),
                ('time_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_value', models.CharField(max_length=50)),
                ('total_nodes', models.IntegerField()),
                ('data', models.JSONField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dataset')),
            ],
            options={
                'db_table': 'simulation',
            },
        ),
    ]
