# Generated by Django 3.1.2 on 2021-04-06 15:24

import app.shims
import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the dataset', max_length=250, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_simulations', models.IntegerField(default=0)),
                ('total_nodes', models.IntegerField(default=0)),
                ('max_simulation_nodes', models.IntegerField(default=0)),
                ('min_simulation_nodes', models.IntegerField(default=0)),
                ('simulation_attributes', models.JSONField(editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dataset',
            },
            bases=(app.shims.DatasetShim, models.Model),
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_nodes', models.IntegerField(editable=False)),
                ('data', models.JSONField(editable=False)),
                ('dataset', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='app.dataset')),
            ],
            options={
                'db_table': 'simulation',
            },
        ),
    ]
