# Generated by Django 3.1.2 on 2021-04-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='simulation_value',
        ),
    ]
