# Generated by Django 3.1.2 on 2021-03-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node2',
            fields=[
                ('file_id', models.IntegerField(db_index=True)),
                ('node_id', models.IntegerField(db_index=True)),
                ('age_yrs', models.FloatField(null=True)),
                ('resting_heart_rate', models.FloatField(null=True)),
                ('active_heart_rate', models.FloatField(null=True)),
                ('blood_pressure', models.FloatField()),
                ('temperature', models.FloatField()),
                ('covid_antibodies', models.FloatField()),
                ('influenza_antibodies', models.FloatField()),
                ('height_in', models.FloatField()),
                ('weight_lbs', models.FloatField()),
                ('bmi', models.FloatField()),
                ('num_teeth', models.FloatField(null=True)),
                ('time_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Node3',
            fields=[
                ('file_id', models.IntegerField(db_index=True)),
                ('node_id', models.IntegerField(db_index=True)),
                ('Date', models.CharField(max_length=20)),
                ('BUDAPEST', models.FloatField()),
                ('BARANYA', models.FloatField()),
                ('BACS', models.FloatField()),
                ('BEKES', models.FloatField()),
                ('BORSOD', models.FloatField()),
                ('CSONGRAD', models.FloatField()),
                ('FEJER', models.FloatField()),
                ('GYOR', models.FloatField()),
                ('HAJDU', models.FloatField()),
                ('HEVES', models.FloatField()),
                ('JASZ', models.FloatField()),
                ('KOMAROM', models.FloatField()),
                ('NOGRAD', models.FloatField()),
                ('PEST', models.FloatField()),
                ('SOMOGY', models.FloatField()),
                ('SZABOLCS', models.FloatField()),
                ('TOLNA', models.FloatField()),
                ('VAS', models.FloatField()),
                ('VESZPREM', models.FloatField()),
                ('ZALA', models.FloatField()),
                ('time_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
