# Generated by Django 3.1.2 on 2021-04-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dataset_simulation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='file_name',
            field=models.CharField(default='main_table_1.csv', max_length=255),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='max_simulation_nodes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='min_simulation_nodes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='total_nodes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='total_simulations',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
