# Generated by Django 3.1.2 on 2021-04-12 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210412_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='file',
            new_name='datafile',
        ),
    ]
