# Generated by Django 3.1.2 on 2021-04-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_datafile_number_of_lines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='max_simulation_nodes',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='min_simulation_nodes',
        ),
        migrations.AddField(
            model_name='dataset',
            name='number_of_nodes_added',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Created'), (1, 'Seeding'), (2, 'Completed'), (3, 'Error'), (4, 'Legacy')], default=4),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='total_nodes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='total_simulations',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
