# Generated by Django 3.1.2 on 2021-04-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210418_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='simulation',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='simulation_index',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
